services:
  app:
    image: mcr.microsoft.com/devcontainers/universal:latest
    command: sleep infinity

  mysql:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
